
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:          
  - runner_test
  - build
  - update_ECR

prologue-job:
  stage: runner_test
  script:
    - echo "Runner is starting . . ."

frontend-build:
  stage: build
  image: docker:latest
  services:
    - docker:23.0.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker --version
  script:
    - echo "Building frontend Docker image..."
    - docker build -t app-frontend ./frontend
  only:
    - main

backend-build:
  stage: build
  image: docker:latest
  services:
    - docker:23.0.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker --version
  script:
    - echo "Building backend Docker image..."
    - docker build -t app-backend ./backend2
  only:
    - main

aws-job:
  stage: update_ECR
  image: docker:latest
  services:
    - docker:23.0.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache python3 py3-pip
    - python3 -m venv /venv
    - . /venv/bin/activate
    - pip install awscli
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  script:
    - docker --version
    - aws --version
    - docker tag app-frontend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/dimgroz-ecr-dr/app-frontend:latest
    - docker tag app-backend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/dimgroz-ecr-dr/app-backend:latest
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/dimgroz-ecr-dr/app-frontend:latest
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/dimgroz-ecr-dr/app-backend:latest

  only:
    - main
  when: manual
