# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

variables:
  AWS_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  ECR_NAME: dimgroz-ecr-dr

stages:          
  - runner_test
  - test
  - update_ECR

prologue-job:
  stage: runner_test
  script:
    - echo "Runner is starting . . ."

compile-and-tests:
  stage: test
  image: maven:3.8.6-jdk-21
  script:
    - echo "Running Maven tests..."
    - cd backend2
    - mvn test

test-builds:
  stage: test
  image: docker:latest
  services:
    - docker:23.0.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t app-frontend ./frontend
    - docker build -t app-backend ./backend2
  only:
    - development

aws-job:
  stage: update_ECR
  image: docker:latest
  services:
    - docker:23.0.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache python3 py3-pip
    - python3 -m venv /venv
    - . /venv/bin/activate
    - pip install awscli
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_REGISTRY
  script:
    - docker build -t app-frontend ./frontend
    - docker build -t app-backend ./backend2

    - docker tag app-frontend $AWS_REGISTRY/$ECR_NAME:frontend-latest
    - docker tag app-backend $AWS_REGISTRY/$ECR_NAME:backend-latest
    
    - docker push $AWS_REGISTRY/$ECR_NAME:frontend-latest
    - docker push $AWS_REGISTRY/$ECR_NAME:backend-latest

  only:
    - main
  when: manual
