
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:          
  - runner_test
  - build
  - update_ECR

prologue-job:
  stage: runner_test
  script:
    - echo "Runner is starting . . ."

frontend-build:
  stage: build
  image: node:20
  script:
    - echo "Building frontend Docker image..."
    - docker build -t app-frontend ./frontend
  only:
    - main

backend-build:
  stage: build
  image: maven:3.9.5-eclipse-temurin-21
  script:
    - echo "Building backend Docker image..."
    - docker build -t app-backend ./backend2
  only:
    - main

aws-job:
  stage: update_ECR
  script:
    - echo "Ready to be puched!"
  only:
    - main
