
services:

  db-service:
    image: postgres:15-alpine
    hostname: postgres_db
    env_file:
      - database.env
    ports:
      - "6543:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/

  backend:
    image: openjdk:21-jdk
    container_name: spring_backend
    build:
      context: ./backend2
      dockerfile: Dockerfile
    env_file:
      - database.env
    ports:
      - "5000:5000"
    depends_on:
      - db-service

  frontend:
    image: node:20.18.0
    container_name: react_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      REACT_APP_API_URL: http://localhost:5000
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data: