
services:

  db-service:
    image: postgres:15-alpine
    hostname: postgres_db
    env_file:
      - database.env
    ports:
      - "6543:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/

  backend:
    image: openjdk:21-jdk
    container_name: spring_backend
    build:
      context: ./backend2
      dockerfile: Dockerfile
    env_file:
      - database.env
    environment:
      CORS_ALLOWED_ORIGINS: "http://localhost:3000"
      KEYCLOAK_URL: "http://keycloak:8080"
      KEYCLOAK_REALM: "votaroTest"
      BACKEND_KEYCLOAK_CLIENT_ID: "backend"
      BACKEND_KEYCLOAK_CLIENT_SECRET: "NZvfUN527Qa9NsEgD0pw6rgFW7dX6zrF"
    ports:
      - "5000:5000"
    depends_on:
      - db-service

  frontend:
    image: node:20.18.0
    container_name: react_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  keycloak_db:
    image: postgres:15-alpine
    container_name: keycloak_postgres
    env_file:
      - keycloak.env
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    ports:
      - "6544:5432"
  
  keycloak:
    image: keycloak/keycloak:latest
    ports:
      - "8080:8080"
    env_file:
      - keycloak.env
    environment:
      - KEYCLOAK_FRONTEND_URL=http://localhost:8080
    depends_on:
      - keycloak_db
    command: "start-dev"
    volumes:
      - keycloak-data:/opt/keycloak/data
      - keycloak-logs:/opt/keycloak/logs


volumes:
  db-data:
  keycloak-db-data:
  keycloak-data:
  keycloak-logs: