
services:

  db:
    image: postgres:latest
    hostname: postgres_db
    env_file:
      - database.env
    ports:
      - "6543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  backend:
    image: openjdk:21-jdk
    container_name: spring_backend
    build:
      context: ./backend2
      dockerfile: Dockerfile
    env_file:
      - ./backend2/MyChoiceApp/MyChoiceApp/database.env
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    image: node:20.18.0
    container_name: react_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: http://backend:5000
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data: