apiVersion: apps/v1
kind: {{ .Values.backend.kind }}
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: {{ .Values.backend.container.name }}
          image: {{ .Values.backend.container.image }}
          imagePullPolicy: {{ .Values.backend.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.container.port | int }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.backend.container.env.dbUrl }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
