apiVersion: apps/v1
kind: {{ .Values.backend.kind }}
metadata:
  name: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.label }}
    spec:
      containers:
        - name: {{ .Values.backend.container.name }}
          image: {{ .Values.backend.container.image }}
          imagePullPolicy: {{ .Values.backend.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.container.port | int }}
          env:
            - name: CORS_ALLOWED_ORIGINS
              value: "{{ .Values.backend.cors.allowedOrigins }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secret.name }}
                  key: DATABASE_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secret.name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secret.name }}
                  key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  label: {{ .Values.backend.label }}
spec:
  selector:
    app: {{ .Values.backend.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      name: {{ .Values.backend.service.portName }}
  type: {{ .Values.backend.service.type }}
