apiVersion: apps/v1
kind: {{ .Values.db.kind }}
metadata:
  name: {{ .Values.db.name }}
  labels:
    app: {{ .Values.db.controllerlabel }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.db.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.label }}
    spec:
      containers:
        - name: {{ .Values.db.container.name }}
          image: {{ .Values.db.container.image }}
          ports:
            - containerPort: {{ .Values.db.container.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secret.name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secret.name }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secret.name }}
                  key: POSTGRES_DB

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
spec:
  selector:
    app: {{ .Values.db.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}
  type: {{ .Values.db.service.type }}
