apiVersion: apps/v1
kind: {{ .Values.frontend.kind }}
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.label }}
    spec:
      containers:
        - name: {{ .Values.frontend.container.name }}
          image: {{ .Values.frontend.container.image }}
          imagePullPolicy: {{ .Values.frontend.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.container.port }}
          env:
            - name: REACT_APP_BACKEND_URL
              value: {{ .Values.frontend.container.env.backendUrl }}
            - name: REACT_APP_KEYCLOAK_URL
              value: testM
            - name: REACT_APP_KEYCLOAK_REALM
              value: {{ .Values.keycloak.env.realmName }}
            - name: REACT_APP_KEYCLOAK_CLIENT_ID
              value: {{ .Values.keycloak.env.frontendClientId }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  labels:
    app: {{ .Values.frontend.label }}
spec:
  selector:
    app: {{ .Values.frontend.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      name: {{ .Values.frontend.service.portName }}
  type: {{ .Values.frontend.service.type }}
