apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: vote-app-development
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:722377226063:certificate/8f6bdeee-aad4-485a-97f3-26767bed4a9e
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.service.name }}
                port:
                  number: {{ .Values.frontend.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.service.name }}
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.keycloak.service.name }}
                port:
                  number: {{ .Values.keycloak.service.port }}
          - path: /realms
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.keycloak.service.name }}
                port:
                  number: {{ .Values.keycloak.service.port }}
          - path: /protocol
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.keycloak.service.name }}
                port:
                  number: {{ .Values.keycloak.service.port }}