backend:
  cors:
    allowedOrigins: http://www.votarodev.org, af4d634caa3bf41f4a24902c29759bb0-1731034313.eu-central-1.elb.amazonaws.com
ingress:
  name: ingress-dev
  namespace: dev
  hostname: www.votarodev.org