db:
  kind: Deployment
  replicas: 1
  secret:
    name: db-secret
  container:
    name: postgres-db
    image: postgres:15-alpine
    port: 5432
  service:
    name: db-service
    port: 5432
    targetPort: 5432

backend:
  kind: Deployment
  replicas: 1
  container:
    name: backend
    image: 722377226063.dkr.ecr.eu-central-1.amazonaws.com/dimgroz-ecr-dr:backend-0.0.v9473
    imagePullPolicy: Always
    port: 5000
  service:
    name: backend-service
    port: 5000
    targetPort: 5000
  cors:
    allowedOrigins: http://localhost:3000

frontend:
  kind: Deployment
  replicas: 1
  container: 
    name: frontend
    image: 722377226063.dkr.ecr.eu-central-1.amazonaws.com/dimgroz-ecr-dr:frontend-0.0.v9473
    imagePullPolicy: Always
    port: 3000
    env:
      backendUrl: http://backend-service:5000
  service:
    type: NodePort
    name: frontend-service
    port: 3000
    targetPort: 3000

ingress:
  name: ingress
  namespace: dev
  hostname: www.votaro.org
